/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new user */
        post: operations["registerUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login user */
        post: operations["loginUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chart/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate a birth chart */
        post: operations["generateChart"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chart/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a saved chart */
        get: operations["getChart"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chart/test/calculate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Test chart calculation */
        get: operations["testCalculation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reading/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get available reading categories */
        get: operations["getReadingCategories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reading/{chartId}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get AI-generated summary reading */
        get: operations["getSummaryReading"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reading/{chartId}/{category}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get category-specific reading */
        get: operations["getCategoryReading"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reading/{chartId}/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask a follow-up question */
        post: operations["askQuestion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reading/{chartId}/cached": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get cached readings for a chart */
        get: operations["getCachedReadings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subscription/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get subscription status */
        get: operations["getSubscriptionStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterRequest: {
            /** @example John Doe */
            name: string;
            /**
             * Format: email
             * @example john@example.com
             */
            email: string;
            /** @example securePassword123 */
            password: string;
        };
        LoginRequest: {
            /**
             * Format: email
             * @example john@example.com
             */
            email: string;
            /** @example securePassword123 */
            password: string;
        };
        AuthResponse: {
            success?: boolean;
            message?: string;
            /** @description JWT token */
            token?: string;
            user?: components["schemas"]["User"];
        };
        User: {
            /** Format: uuid */
            id?: string;
            name?: string;
            /** Format: email */
            email?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        UserResponse: {
            success?: boolean;
            user?: components["schemas"]["User"];
        };
        ChartRequest: {
            /**
             * @description Name of the person (optional)
             * @example John Doe
             */
            name?: string;
            /**
             * @description Birth date in YYYY-MM-DD format
             * @example 1990-05-15
             */
            birthDate: string;
            /**
             * @description Birth time in HH:MM format (24-hour)
             * @example 14:30
             */
            birthTime: string;
            /**
             * @description Birth place name (optional, for display)
             * @example New York, NY, USA
             */
            place?: string;
            /** @example 40.7128 */
            latitude: number;
            /** @example -74.006 */
            longitude: number;
            /**
             * @description IANA timezone identifier
             * @example America/New_York
             */
            timezone?: string;
        };
        ChartResponse: {
            success?: boolean;
            chart?: components["schemas"]["BirthChart"];
        };
        BirthChart: {
            /** Format: uuid */
            id: string;
            /** @description Name of the person */
            name?: string;
            /** Format: date-time */
            birthDate: string;
            birthTime: string;
            /** @description Birth place name */
            place?: string;
            latitude: number;
            longitude: number;
            timezone: string;
            ascendant: components["schemas"]["Planet"];
            planets: components["schemas"]["Planet"][];
            houses: components["schemas"]["House"][];
            dashas: components["schemas"]["DashaPeriod"][];
            /** @description Ayanamsa value in degrees */
            ayanamsa: number;
            /** @example Lahiri */
            ayanamsaName: string;
            /** Format: date-time */
            calculatedAt: string;
        };
        Planet: {
            /** @enum {string} */
            name: "Sun" | "Moon" | "Mars" | "Mercury" | "Jupiter" | "Venus" | "Saturn" | "Rahu" | "Ketu";
            /** @enum {string} */
            sign: "Aries" | "Taurus" | "Gemini" | "Cancer" | "Leo" | "Virgo" | "Libra" | "Scorpio" | "Sagittarius" | "Capricorn" | "Aquarius" | "Pisces";
            signIndex: number;
            degree: number;
            longitude: number;
            nakshatra: string;
            nakshatraPada: number;
            house: number;
            isRetrograde: boolean;
        };
        House: {
            number: number;
            sign: string;
            signIndex: number;
            degree: number;
            longitude: number;
        };
        DashaPeriod: {
            planet: string;
            /** Format: date-time */
            startDate: string;
            /** Format: date-time */
            endDate: string;
            /** @enum {string} */
            level: "maha" | "antar" | "pratyantar";
        };
        CategoriesResponse: {
            success?: boolean;
            categories?: components["schemas"]["ReadingCategory"][];
        };
        ReadingCategory: {
            /** @enum {string} */
            id?: "summary" | "love" | "career" | "finances" | "health" | "timeline";
            name?: string;
            description?: string;
        };
        ReadingResponse: {
            success?: boolean;
            reading?: components["schemas"]["Reading"];
        };
        Reading: {
            category: string;
            content: string;
            cached: boolean;
            /** Format: uuid */
            chartId: string;
            /** Format: date-time */
            generatedAt: string;
        };
        ChatRequest: {
            question: string;
            previousReadings?: string[];
        };
        ChatResponse: {
            success?: boolean;
            response?: string;
            chartId?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        CachedReadingsResponse: {
            success?: boolean;
            chartId?: string;
            cachedReadings?: {
                category?: string;
                /** Format: date-time */
                createdAt?: string;
                hasContent?: boolean;
            }[];
        };
        SubscriptionStatus: {
            success?: boolean;
            subscription?: {
                /** @enum {string} */
                plan?: "free" | "premium" | "pro";
                /** @enum {string} */
                status?: "active" | "cancelled" | "expired";
                /** Format: date-time */
                expiresAt?: string | null;
                features?: string[];
            };
        };
        Error: {
            /** @example false */
            success?: boolean;
            error?: string;
            message?: string;
            path?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status?: string;
                        /** Format: date-time */
                        timestamp?: string;
                        /** @example jyotish-backend */
                        service?: string;
                    };
                };
            };
        };
    };
    registerUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description User registered successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Invalid request data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Email already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    loginUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Login successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user info */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    generateChart: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChartRequest"];
            };
        };
        responses: {
            /** @description Chart generated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChartResponse"];
                };
            };
            /** @description Invalid birth details */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getChart: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Chart ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Chart retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChartResponse"];
                };
            };
            /** @description Chart not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    testCalculation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Test calculation successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success?: boolean;
                        message?: string;
                        chart?: components["schemas"]["BirthChart"];
                    };
                };
            };
        };
    };
    getReadingCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of available categories */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoriesResponse"];
                };
            };
        };
    };
    getSummaryReading: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Chart ID */
                chartId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Summary reading generated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadingResponse"];
                };
            };
            /** @description Chart not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description AI service unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getCategoryReading: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Chart ID */
                chartId: string;
                /** @description Reading category */
                category: "summary" | "love" | "career" | "finances" | "health" | "timeline";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reading generated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadingResponse"];
                };
            };
            /** @description Invalid category */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Chart not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    askQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Chart ID */
                chartId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Question answered */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Chart not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getCachedReadings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Chart ID */
                chartId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cached readings list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CachedReadingsResponse"];
                };
            };
        };
    };
    getSubscriptionStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Subscription status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionStatus"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
